name: API Response Time Gate

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  api-response-time-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout testapi repository
        uses: actions/checkout@v4

      - name: Clone api-response-time-tester repository
        run: |
          git clone https://github.com/Abhishekbisht28/api-response-time-tester.git

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Django dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django djangorestframework

      - name: Start Django server
        run: |
          python manage.py runserver 127.0.0.1:9000 &
          sleep 8

      - name: Verify Django API is running
        run: |
          curl http://127.0.0.1:9000/api/overview/

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Run Maven API Response Tests
        run: |
          cd api-response-time-tester
          mvn clean verify

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-report
          path: api-response-time-tester/target/